[[redirects]]
  from = "/profiles/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/template/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/count.js"
  to = "https://gc.zgo.at/count.js"
  status = 200
