[[redirects]]
  from = "/profiles/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/template/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/hello.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 202
